"""Tiny i18n layer for the Auto Research template.

Language is chosen with the ``OUTPUT_LANGUAGE`` environment variable (set via a
GitHub Actions Variable or Secret). Supported values:

* ``en`` (default) — English
* ``ja`` — Japanese / 日本語

Anything unrecognised falls back to English.

Claude (in the research step) writes the *content* in the chosen language; this
module only localises the deterministic Markdown scaffolding that the Python
publisher wraps around that content (headings, field labels, the Slack line).
"""

from __future__ import annotations

import os

DEFAULT_LANGUAGE = "en"
SUPPORTED = ("en", "ja")


def get_language() -> str:
    """Return the normalised output language code (``en`` or ``ja``)."""
    raw = os.environ.get("OUTPUT_LANGUAGE", "").strip().lower()
    if raw in {"ja", "jp", "japanese", "日本語"}:
        return "ja"
    if raw in {"en", "english"}:
        return "en"
    return DEFAULT_LANGUAGE


# --- Localised strings ------------------------------------------------------
# Each entry is keyed by language. Values may contain ``{...}`` placeholders
# that callers fill in with str.format().
_STRINGS: dict[str, dict[str, str]] = {
    "topic_label": {
        "en": "Topic",
        "ja": "テーマ",
    },
    # Section display names (used in issue titles + the Slack line). These name the
    # three generic layers every domain produces — foundations (the unwavering
    # facts), the latest developments, and the takes/interpretations — so they read
    # naturally whether the run's domain is research, tech, business, hobby, or
    # finance. The internal section keys + label tags stay (news/hypotheses/related).
    "section_news": {"en": "Latest", "ja": "最新情報"},
    "section_hypotheses": {"en": "Takes", "ja": "考察"},
    "section_related": {"en": "Foundations", "ja": "事実・基礎"},
    "section_watch": {"en": "Site Watch", "ja": "サイト監視"},
    # --- Publisher scaffolding (Python renders these around Claude's content) ---
    "pub_date": {"en": "Date", "ja": "日付"},
    "pub_source": {"en": "Source", "ja": "出典"},
    "pub_link": {"en": "Link", "ja": "リンク"},
    "pub_theme": {"en": "Theme", "ja": "テーマ区分"},
    "pub_rationale": {"en": "Rationale", "ja": "根拠"},
    "pub_experiment": {"en": "Experiment", "ja": "検証実験"},
    "pub_risk": {"en": "Risk / confound", "ja": "リスク・交絡"},
    "pub_open_gaps": {"en": "Open gaps", "ja": "未解決の課題"},
    # --- Site Watch (publish_watch.py renders these around Claude's diff summary) ---
    "watch_url_label": {"en": "Watched page", "ja": "監視ページ"},
    "watch_lines": {"en": "Lines changed", "ja": "変更行数"},
    "watch_changes": {"en": "What changed", "ja": "変更点"},
    "watch_default_headline": {"en": "Page updated", "ja": "ページが更新されました"},
    "watch_slack_header": {
        "en": "{emoji} *Site Watch* — {name}",
        "ja": "{emoji} *サイト監視* — {name}",
    },
    "pub_footer": {
        "en": (
            "---\n_Generated by Auto Research via Claude Code. Sources were "
            "retrieved with live web search — please verify before citing._"
        ),
        "ja": (
            "---\n_このIssueは Auto Research（Claude Code）により生成されました。"
            "出典はWeb検索で取得しています。引用前に内容をご確認ください。_"
        ),
    },
    # --- Prior-context digest (existing_context.py, read by the research step) ---
    "ctx_header": {
        "en": (
            "Items ALREADY published in previous runs ({count} issue(s) below). "
            "Do NOT propose anything that duplicates these — find genuinely NEW "
            "material not listed here:"
        ),
        "ja": (
            "過去の実行で既に発行済みの項目です（以下の{count}件のIssue）。"
            "これらと重複する内容は提案せず、ここに無い新しい項目を見つけてください："
        ),
    },
    "fb_good": {
        "en": (
            "FEEDBACK — the lab marked these past items GOOD (a 👍 reaction or a good "
            "label). Produce MORE work in this direction / style (without duplicating "
            "the specific items):"
        ),
        "ja": (
            "フィードバック — ラボが「good」と評価した過去の項目です（👍 リアクション"
            "または good ラベル）。この方向性・スタイルの項目をより多く出してください"
            "（具体的な項目自体は重複させないこと）："
        ),
    },
    "fb_bad": {
        "en": (
            "FEEDBACK — the lab marked these past items BAD (a 👎 reaction or a bad "
            "label). AVOID this kind of topic, source, or framing in your output:"
        ),
        "ja": (
            "フィードバック — ラボが「bad」と評価した過去の項目です（👎 リアクション"
            "または bad ラベル）。このようなトピック・出典・切り口は避けてください："
        ),
    },
    "ctx_none": {
        "en": "No prior Issues were found for this section. Nothing to avoid — research freely.",
        "ja": "このセクションの過去Issueは見つかりませんでした。重複を避ける必要はなく、自由にリサーチしてください。",
    },
    # --- Slack: one post per title (the section emoji leads the line) -----------
    "slack_item": {
        "en": "{emoji} *Auto Research* — {section}: {title}\n{url}",
        "ja": "{emoji} *自動リサーチ* — {section}: {title}\n{url}",
    },
    "slack_item_nolink": {
        "en": "{emoji} *Auto Research* — {section}: {title}",
        "ja": "{emoji} *自動リサーチ* — {section}: {title}",
    },
    # --- Slack: digest mode (SLACK_DIGEST=true) — one post for the whole section ---
    # A single header line, then one compact bullet per item below it.
    "slack_digest_header": {
        "en": "{emoji} *Auto Research* — {section} ({count})",
        "ja": "{emoji} *自動リサーチ* — {section}（{count}件）",
    },
    "slack_digest_item": {
        "en": "• {title}\n{url}",
        "ja": "• {title}\n{url}",
    },
    "slack_digest_item_nolink": {
        "en": "• {title}",
        "ja": "• {title}",
    },
    # --- Combined run notification (notify_combined.py folds the four parallel
    # section jobs into ONE Slack post + ONE email per run). The run header leads
    # the message; each section then appears under a compact sub-header (no
    # repeated "Auto Research", which the run header already carries). -----------
    "slack_run_header": {
        "en": "🔬 *Auto Research* — {date}",
        "ja": "🔬 *自動リサーチ* — {date}",
    },
    "slack_run_subject": {
        "en": "Auto Research — {date}",
        "ja": "自動リサーチ — {date}",
    },
    "slack_section_header": {
        "en": "{emoji} *{section}* ({count})",
        "ja": "{emoji} *{section}*（{count}件）",
    },
    # The PRIMARY link in every Slack/email line is the item's own page on the
    # generated GitHub Pages site (many readers never open GitHub). The source
    # Issue is demoted to this small secondary line — and only shown when the
    # site link is leading; when Pages isn't set up the Issue becomes the primary
    # link instead and this line is omitted.
    "slack_issue_link": {
        "en": "↳ GitHub Issue: {url}",
        "ja": "↳ GitHub Issue: {url}",
    },
    # --- Static site (build_site.py renders a GitHub Pages site from the Issues) ---
    "site_title": {"en": "Auto Research", "ja": "Auto Research"},
    "site_tagline": {
        "en": "A living, web-grounded research briefing — one page per run.",
        "ja": "Webに基づく、生きた研究ブリーフィング — 実行ごとに1ページ。",
    },
    "site_runs": {"en": "runs", "ja": "回の実行"},
    "site_items": {"en": "items", "ja": "件"},
    "site_latest": {"en": "Latest run", "ja": "最新の実行"},
    "site_run_heading": {"en": "Research run", "ja": "リサーチ実行"},
    "site_view_issue": {"en": "View Issue →", "ja": "Issueを見る →"},
    "site_back": {"en": "← All runs", "ja": "← すべての実行"},
    "site_no_runs": {
        "en": "No research Issues yet. Once Auto Research files some, they appear here.",
        "ja": "まだ研究Issueがありません。Auto Researchが発行すると、ここに表示されます。",
    },
    "site_empty_run": {
        "en": "No items recorded for this run.",
        "ja": "この実行には項目が記録されていません。",
    },
    "site_generated": {
        "en": "Generated by Auto Research via Claude Code · {timestamp}",
        "ja": "Auto Research（Claude Code）により生成 · {timestamp}",
    },
    "site_view_on_github": {"en": "View on GitHub", "ja": "GitHubで見る"},
    "site_comments": {"en": "{count} comment(s)", "ja": "コメント {count} 件"},
    "site_run_desc": {
        "en": "{count} item(s) from the research run on {date}.",
        "ja": "{date} のリサーチ実行（{count} 件）。",
    },
    "site_tag_desc": {
        "en": "{count} item(s) tagged “{tag}”.",
        "ja": "「{tag}」タグの項目（{count} 件）。",
    },
    # --- Section / reaction browse pages + item detail pages --------------------
    "site_section_desc": {
        "en": "Every item in {name} ({count}), newest first.",
        "ja": "{name}のすべての項目（{count} 件・新しい順）。",
    },
    "site_reaction_desc": {
        "en": "{count} item(s) the lab reacted to with {emoji} {name}.",
        "ja": "{emoji} {name} のリアクションが付いた項目（{count} 件）。",
    },
    "site_back_run": {"en": "← {date} run", "ja": "← {date} の実行"},
    "site_comments_heading": {"en": "Comments", "ja": "コメント"},
    # Reaction display names (the eight GitHub reactions).
    "react_plus1": {"en": "Liked", "ja": "高評価"},
    "react_minus1": {"en": "Disliked", "ja": "低評価"},
    "react_heart": {"en": "Loved", "ja": "お気に入り"},
    "react_hooray": {"en": "Celebrated", "ja": "祝福"},
    "react_rocket": {"en": "Rocket", "ja": "ロケット"},
    "react_laugh": {"en": "Funny", "ja": "笑い"},
    "react_eyes": {"en": "Watching", "ja": "注目"},
    "react_confused": {"en": "Confused", "ja": "困惑"},
}


def t(key: str, **kwargs: object) -> str:
    """Return the localised string for ``key``, formatted with ``kwargs``."""
    lang = get_language()
    entry = _STRINGS[key]
    # Distinguish a missing language from an intentionally empty string (``""``
    # is falsy, so ``or`` would wrongly fall back to English for it).
    template = entry[lang] if lang in entry else entry[DEFAULT_LANGUAGE]
    return template.format(**kwargs) if kwargs else template
